// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.3.0
//   protoc               v3.20.3
// source: custom_enums/v1/custom_enums.proto

/* eslint-disable */

export const protobufPackage = "custom_enums.v1";

/**
 * Статусы операций
 *  http status codes
 *    https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
 *  gRPC status codes
 *    https://grpc.github.io/grpc/core/md_doc_statuscodes.html
 */
export enum OperationStatus {
  /** OPERATION_STATUS_UNSPECIFIED - Дефолтный (неопределенный) статус операции */
  OPERATION_STATUS_UNSPECIFIED = "OPERATION_STATUS_UNSPECIFIED",
  /**
   * OPERATION_STATUS_OK - Статус операции сигнализирующий о корректом завершении операции
   *  http analog status code: 200
   *  gRPC analog status code: 1
   */
  OPERATION_STATUS_OK = "OPERATION_STATUS_OK",
  /**
   * OPERATION_STATUS_ERROR - Статус операции сигнализирующий о не корректом завершении операции
   *  http analog status code: 400
   *  gRPC analog status code: 8,9,11
   */
  OPERATION_STATUS_ERROR = "OPERATION_STATUS_ERROR",
  /**
   * OPERATION_STATUS_NOT_PERMITTED - Статус операции сигнализирующий о недостаточном наборе прав для его вызова
   *  http analog status code: 403
   *  gRPC analog status code: 7
   */
  OPERATION_STATUS_NOT_PERMITTED = "OPERATION_STATUS_NOT_PERMITTED",
  /**
   * OPERATION_STATUS_DUPLICATE - Статус операции сигнализирующий о том что операция продублирована
   *  http analog status code: 409
   *  gRPC analog status code: 6
   */
  OPERATION_STATUS_DUPLICATE = "OPERATION_STATUS_DUPLICATE",
  /**
   * OPERATION_STATUS_SERVER_ERROR - Статус операции сигнализирующий о не корректой обработке со стороны сервера
   *  http analog status code: 500
   *  gRPC analog status code: 13,14,15
   */
  OPERATION_STATUS_SERVER_ERROR = "OPERATION_STATUS_SERVER_ERROR",
  /**
   * OPERATION_STATUS_NO_DATA - Статус операции сигнализирующий о том, что данных по запросу не обнаружено
   *  http analog status code: 204
   *  gRPC analog status code: 5
   */
  OPERATION_STATUS_NO_DATA = "OPERATION_STATUS_NO_DATA",
  /** OPERATION_STATUS_DECLINED - Статус операции сигнализирующий о том, что при текущих условиях операцию выполнить нельзя */
  OPERATION_STATUS_DECLINED = "OPERATION_STATUS_DECLINED",
  /** OPERATION_STATUS_LOCKED - Статус операции - заблокировано */
  OPERATION_STATUS_LOCKED = "OPERATION_STATUS_LOCKED",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export function operationStatusFromJSON(object: any): OperationStatus {
  switch (object) {
    case 0:
    case "OPERATION_STATUS_UNSPECIFIED":
      return OperationStatus.OPERATION_STATUS_UNSPECIFIED;
    case 1:
    case "OPERATION_STATUS_OK":
      return OperationStatus.OPERATION_STATUS_OK;
    case 2:
    case "OPERATION_STATUS_ERROR":
      return OperationStatus.OPERATION_STATUS_ERROR;
    case 3:
    case "OPERATION_STATUS_NOT_PERMITTED":
      return OperationStatus.OPERATION_STATUS_NOT_PERMITTED;
    case 4:
    case "OPERATION_STATUS_DUPLICATE":
      return OperationStatus.OPERATION_STATUS_DUPLICATE;
    case 5:
    case "OPERATION_STATUS_SERVER_ERROR":
      return OperationStatus.OPERATION_STATUS_SERVER_ERROR;
    case 6:
    case "OPERATION_STATUS_NO_DATA":
      return OperationStatus.OPERATION_STATUS_NO_DATA;
    case 7:
    case "OPERATION_STATUS_DECLINED":
      return OperationStatus.OPERATION_STATUS_DECLINED;
    case 8:
    case "OPERATION_STATUS_LOCKED":
      return OperationStatus.OPERATION_STATUS_LOCKED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return OperationStatus.UNRECOGNIZED;
  }
}

export function operationStatusToJSON(object: OperationStatus): string {
  switch (object) {
    case OperationStatus.OPERATION_STATUS_UNSPECIFIED:
      return "OPERATION_STATUS_UNSPECIFIED";
    case OperationStatus.OPERATION_STATUS_OK:
      return "OPERATION_STATUS_OK";
    case OperationStatus.OPERATION_STATUS_ERROR:
      return "OPERATION_STATUS_ERROR";
    case OperationStatus.OPERATION_STATUS_NOT_PERMITTED:
      return "OPERATION_STATUS_NOT_PERMITTED";
    case OperationStatus.OPERATION_STATUS_DUPLICATE:
      return "OPERATION_STATUS_DUPLICATE";
    case OperationStatus.OPERATION_STATUS_SERVER_ERROR:
      return "OPERATION_STATUS_SERVER_ERROR";
    case OperationStatus.OPERATION_STATUS_NO_DATA:
      return "OPERATION_STATUS_NO_DATA";
    case OperationStatus.OPERATION_STATUS_DECLINED:
      return "OPERATION_STATUS_DECLINED";
    case OperationStatus.OPERATION_STATUS_LOCKED:
      return "OPERATION_STATUS_LOCKED";
    case OperationStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export function operationStatusToNumber(object: OperationStatus): number {
  switch (object) {
    case OperationStatus.OPERATION_STATUS_UNSPECIFIED:
      return 0;
    case OperationStatus.OPERATION_STATUS_OK:
      return 1;
    case OperationStatus.OPERATION_STATUS_ERROR:
      return 2;
    case OperationStatus.OPERATION_STATUS_NOT_PERMITTED:
      return 3;
    case OperationStatus.OPERATION_STATUS_DUPLICATE:
      return 4;
    case OperationStatus.OPERATION_STATUS_SERVER_ERROR:
      return 5;
    case OperationStatus.OPERATION_STATUS_NO_DATA:
      return 6;
    case OperationStatus.OPERATION_STATUS_DECLINED:
      return 7;
    case OperationStatus.OPERATION_STATUS_LOCKED:
      return 8;
    case OperationStatus.UNRECOGNIZED:
    default:
      return -1;
  }
}
