export const QUERY_KEYS = {
  USERS: "users",
  TARIFFS: "tariffs",
  CLIENT_TARIFFS: "client_tariffs",
  USER: "user",
  CURRENT_USER: "current_user",
  COUNTRIES: "countries",
  ROLES: "roles",
  ORDERS: "orders",
  CLIENT_ORDERS: "client_orders",
  PERMISSIONS: "permissions",
  METHODS: "methods",
  RESET_PASSWORD: "reset_password",
  REQUISITES: "requisites",
  INVOICES: "invoices",
  DETAILED_USER: "detailed_user",
  HISTORIES: "histories",
  HISTORIES_BY_USER: "histories_by_user",
  DETAILED_HISTORIES: "detailed_histories",
};
