replicaCount: 1

image:
  repository: registry.quckoo.net/api-tips/api-tips-frontend
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: 
  - name: "api-tips-secret"

nameOverride: ""
fullnameOverride: ""

imagePull:
  credentials: ""
  secretName: "api-tips-secret"

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 3000
  portName: http
  protocol: TCP

ingress:
  enabled: false
  className: "nginx"
  annotations: 
    kubernetes.io/ingress.class: nginx

resources: 
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 10m
    memory: 10Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

additionalEnvs: []

livenessProbe: {}
readinessProbe: {}
startupProbe: {}
